### ISSUE TITLE
How do I deploy nested_hypervisor with static ip on vcloud

### ISSUE THREAD

**Issue by hemanthgk10** [frapposelli/vagrant-vcloud#103]
Hi

I created an esxi 5.5 box using packer and deployed that on vCloud Director using your plugin. The Deployment works fine but the esx VM fails to power on with the error message.

Bringing machine 'esx1' up with 'vcloud' provider...
==> esx1: Building vApp...
==> esx1: vApp vcd-sample-boxes-root-centos-0-6643738e successfully created.
Invalid request Guest customization is not supported by the selected OS. Please disable guest customization to proceed.

I did mention vcloud.nested_hypervisor = true in the Vagrantfile. VCD assigns an IP from Static IP Pool but as the guest customization doesn't work it fails to power on with above message. When I power it on manually, I see that it the static ip assigned by vCloud is not configured for the esx. How can get I the VM to be configured with the IP assigned by VCD.

Thanks a lot.

**Comment by ryanharper** [comment]
I am stuck here as well, any ideas guys?

**Comment by StefanScherer** [comment]
@hemanthgk10 @ryanharper To disable guest customization, you could try using the PR#104 which has [this feature](https://github.com/frapposelli/vagrant-vcloud/pull/104/files#diff-04c6e90faac2675aa89e2176d2eec7d8R82), but I haven't used it yet.

I've built a gem file containing that PR for personal tests and can be found [in my fork](https://github.com/StefanScherer/vagrant-vcloud/releases/tag/v0.4.4).
