### ISSUE TITLE
Write failed: Broken pipe

### ISSUE THREAD

**Issue by dorheini** [frapposelli/vagrant-vcloud#117]
Hi.
I'm facing an issue with vagrant-vcloud fails due to the mentioned above error.
After some research, i found that it occurs during vagrant copying files (files which in the vagrant project folder) to the VM.
Later on i opened the VM by using VMWare Remote console plugin and i saw that during the process of copying files, the VM auto reboot and this is why i get Broken pipe (While copying a file, the VM reboot).
I asked some IT personal and they told me that auto reboot for VMs in vCloud always happen due to configuring hardware (the VM auto reboot after 3-4 minutes from the first time its powered on).
To verify it, i created a windows VM and powered it on.
After 3-4 minutes it was automatically reboot (just once from the first time it powered on).

Any ideas on how to solve this?

UPDATE: It is more accurate to say that it happens in the phase of sync folder /vagrant

Thanks in advance,
Dor

**Comment by StefanScherer** [comment]
@dorheini I had the same issue with a second reboot. The first reboot is for guest customization and the packer-windows templates I use open the WinRM port after renaming the guest VM. But then there was a second reboot while rsyncing or provisioning the VM. After a couple of retries I found my problem. The VMware Tools in my guest VM's were too old and it seems that these tools are automatically updated.
So try to update the VMware tools in your VM's to the latest (version 9.9.3 AFAIK).

If you use the packer templates from the packer-windows repo, the PR joefitzgerald/packer-windows#162 should be applied.

**Comment by dorheini** [comment]
Hi Stefan.
Thanks for the quick replay.
The VMware tools version depends on the ESX version.
after running the following: vmware-toolbox-cmd -v 
i got: 9.0.10

How can i update it from the guest VM? is it possible at all?
BTW, my VM's OS is Fedora 20 (terminal only, no GUI) and the vCloud director version is 5.1
I Managed to install the VMware tools but as i said before the version is 9.0.10:

![capture](https://cloud.githubusercontent.com/assets/13435000/9464873/1c867f9e-4b30-11e5-8cae-9f80231f4cfa.PNG)


After installing the VMware tools version above, i;m still experiencing the problem of broken pipe due to second reboot while vagrant executes resync action

**Comment by StefanScherer** [comment]
@dorheini I do not have experience with Fedora. But a look at boxcutter/fedora shows me this provision script https://github.com/boxcutter/fedora/blob/master/script/vmtool.sh that uses VMware Tools 9.2.2 or 9.6.0. You might have a look at it.

The boxcutter repos are a good starting point to create Vagrant boxes with packer. We have some of the boxcutter/ubuntu boxes in our vCloud.
