### ISSUE TITLE
VM with multiple NICs

### ISSUE THREAD

**Issue by dorheini** [frapposelli/vagrant-vcloud#118]
Hi.
I am using vagrant vcloud in order to deploy VM with multiple network cards interface.
The vApp template contains VM which has 6 NICs.
When creating a vApp out of this vApp template manually (by using vcloud GUI) i get a VM with 6 NICs.
When using vagrant-vcloud, the VM has a single NIC even though its the same vApp template i mentioned above.

Please advise,
Thanks in advance,
Dor.

**Comment by StefanScherer** [comment]
@dorheini you probably need the PR #104 which seems to be able to add more NICs to the VMs.
I've merged this PR in January to get a special gem for internal use, have a look at https://github.com/StefanScherer/vagrant-vcloud/releases/tag/v0.4.4
(Sorry for the version number conflict with upstream).

See the PR's README for a small example: https://github.com/TechAccelerator/vagrant-vcloud/blob/master/README.md#configuration

To install the gem manually, you have to remove the upstream plugin and then have a look here: https://github.com/StefanScherer/basebox-slave/blob/master/scripts/provision-vmware-slave.sh#L43-L45

I suggest running this in a test environment to keep your production vagrant installation healthy.
