### ISSUE TITLE
Does not work with vCloud Director 8

### ISSUE THREAD

**Issue by ciis0** [frapposelli/vagrant-vcloud#150]
Hello there. :)

Although vCD 8 provides an compatible 5.1 API, vagrant-vcloud sees the highest version (api 9) and fails.

https://github.com/frapposelli/vagrant-vcloud/blob/8da29a4d8fea43871d615a3060b128b66b13946c/lib/vagrant-vcloud/driver/meta.rb#L133-L139

https://github.com/frapposelli/vagrant-vcloud/blob/8da29a4d8fea43871d615a3060b128b66b13946c/lib/vagrant-vcloud/driver/meta.rb#L43-L55

A quick work-around is to comment out the version check and always use `VERSION_5_1`.

As we actively use the plugin in our project we should be able to provide an PR.

Thank you.

**Comment by StefanScherer** [comment]
Have a look at #142, should be in v0.5.0

**Comment by ciis0** [comment]
ah, were at 0.4.4. I guess this can be closed then. :)

**Comment by frapposelli** [comment]
Thanks @StefanScherer for jumping in 👍
