### ISSUE TITLE
How to use existing vApp?

### ISSUE THREAD

**Issue by tknerr** [frapposelli/vagrant-vcloud#20]
Is it possible to use an existing vApp rather than creating a new one from a basebox?

If so, can you give an example of how the vcloud configuration in the Vagrantfile must look like (i.e. minimum required config options)?

**Comment by zubairov** [comment]
@frapposelli do you have some tips on how to create such a box that will refer to existing vApp?

**Comment by StefanScherer** [comment]
@zubairov I don't know if this helps in your case. A dummy box is pretty simple.
I've added a dummy box in this repo: https://github.com/StefanScherer/vcloud-scenarios with some command examples in the README.md.

I think you only have to add such a dummy box for your vApp to tell Vagrant and the vagrant-vcloud plugin this this "box" exists in Vagrant's box cache.

For example:

```bash
vagrant box add name_of_your_vApp https://github.com/StefanScherer/vcloud-scenarios/raw/master/dummy_box/dummy.box
```

**Comment by StefanScherer** [comment]
This dummy box is just a tar file containing a `metadata.json` file with the content `{"provider":"vcloud"}`:

```bash
$ tar tvf dummy.box 
-rw-r--r--  0 root   root       22 May  9  2014 metadata.json

$ tar xvf dummy.box 
x metadata.json

$ cat metadata.json 
{"provider":"vcloud"}
```

**Comment by zubairov** [comment]
Ah, got it. I thought vApp Name have to be specified in the ```metadata.json``` and it's apparently not the case. From your example however I've understood that I just need to name it similar to my vApp in VCloud.

Will the Vagrant try to upload my 'dummy' box?

P.S. Checked your repository, really cool, nice examples will explore them more. Thanks allot for that!

**Comment by StefanScherer** [comment]
@zubairov No, if vagrant finds the vApp with the corresponding name in your catalog, nothing will be uploaded.
