### ISSUE TITLE
Vagrant provision with winrm fails on slow start

### ISSUE THREAD

**Issue by StefanScherer** [frapposelli/vagrant-vcloud#65]
Similar to #56, vagrant up may fail while provisioning with winrm communicator a windows guest.

I'm inside my vOrg and so the edge gateway is not configured which also may result in a faster startup as the bridged mode.

```
$ vagrant up --provider=vcloud
Bringing machine 'tst' up with 'vcloud' provider...
Bringing machine 'tst2' up with 'vcloud' provider...
==> tst: Building vApp...
==> tst: vApp vcloud-win-vagrant-basebox-slave-4a5a5713 successfully created.
==> tst: Setting VM hardware...
==> tst: Powering on VM...
==> tst: Fixed port collision for 22 => 2222. Now on port 2277.
==> tst: Fixed port collision for 3389 => 3389. Now on port 2278.
==> tst: Fixed port collision for 5985 => 55985. Now on port 2279.
==> tst: Forwarding Ports: VM port 22 -> vShield Edge port 2277
==> tst: Forwarding Ports: VM port 3389 -> vShield Edge port 2278
==> tst: Forwarding Ports: VM port 5985 -> vShield Edge port 2279
==> tst: Waiting for SSH Access on 10.115.4.4:2277 ...
==> tst: Warning! Folder sync disabled because the rsync binary is missing.
==> tst: Make sure rsync is installed and the binary can be found in the PATH.
==> tst: Running provisioner: shell...
An error occurred executing a remote WinRM command.

Shell: powershell
Command:             $p = "$Env:SystemRoot"
            if ((Test-Path $p) -and (get-item $p).PSIsContainer) {
              exit 0
            }
            exit 1

if ($LASTEXITCODE) { exit $LASTEXITCODE } else { exit 0 }
Message: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. - connect(2) (http://10.115.4.4:2279)
```

First the SSH port of the windows guest will be checked. As there is also a OpenSSH running in my guest, it finally get a connection. Then tries rsync, but rsync is not in path at the moment. I have to fix this.
Then the WinRM connection fails, perhaps the WinRM is not up and running as fast as the OpenSSH is.
Perhaps a retry loop is also needed here for port 5985.

**Comment by mikecali** [comment]
I encounter issue like this. I am using virtualbox as my provider.

$ vagrant up
Bringing machine 'windows' up with 'virtualbox' provider...
==> windows: Importing base box 'ferventcoder/win2008r2-x64-nocm'...
==> windows: Matching MAC address for NAT networking...
==> windows: Checking if box 'ferventcoder/win2008r2-x64-nocm' is up to date...
==> windows: Setting the name of the VM: windows
==> windows: Clearing any previously set network interfaces...
==> windows: Preparing network interfaces based on configuration...
    windows: Adapter 1: nat
    windows: Adapter 2: hostonly
==> windows: Forwarding ports...
    windows: 3389 (guest) => 3389 (host) (adapter 1)
    windows: 5985 (guest) => 5985 (host) (adapter 1)
    windows: 5985 (guest) => 55985 (host) (adapter 1)
    windows: 5986 (guest) => 55986 (host) (adapter 1)
==> windows: Running 'pre-boot' VM customizations...
==> windows: Booting VM...
==> windows: Waiting for machine to boot. This may take a few minutes...
    windows: WinRM address: 127.0.0.1:5985
    windows: WinRM username: vagrant
    windows: WinRM execution_time_limit: PT2H
    windows: WinRM transport: plaintext
An error occurred executing a remote WinRM command.

Shell: powershell
Command: $ProgressPreference='SilentlyContinue';
hostname
if ($?) { exit 0 } else { if($LASTEXITCODE) { exit $LASTEXITCODE } else { exit 1 } }
Message: uninitialized constant WinRM::WinRMWebService
Did you mean?  WinRM::WinRMWMIError

This error actually produce a running VM. But when I tried to reload the result will be below:

$ vagrant reload
==> windows: Attempting graceful shutdown of VM...
An error occurred executing a remote WinRM command.

Shell: powershell
Command: $ProgressPreference='SilentlyContinue';
hostname
if ($?) { exit 0 } else { if($LASTEXITCODE) { exit $LASTEXITCODE } else { exit 1 } }
Message: uninitialized constant WinRM::WinRMWebService
Did you mean?  WinRM::WinRMWMIError

Here is my linux host environment:

VirtualBox Graphical User Interface
Version 5.1.14 r112924 (Qt5.6.2)

$ vagrant plugin list
hostmanager (1.2.2)
vagrant-cachier (1.2.1, system)
vagrant-vbguest (0.13.0)
winrm (2.1.3)
winrm-fs (1.0.1)

$ vagrant -v
Vagrant 1.8.1

Here is my Vagrantfile:

Vagrant.configure("2") do |config|
  config.vm.define "windows" do |windows|
    windows.vm.box = "ferventcoder/win2008r2-x64-nocm"
    windows.vm.network :private_network, ip: "192.168.58.64"
    windows.vm.network "forwarded_port", host: 3389, guest: 3389
    windows.vm.network :forwarded_port, guest: 5985, host: 5985
    windows.vm.communicator = "winrm"
    windows.winrm.retry_limit = 30
    windows.winrm.retry_delay = 10
    windows.vm.provider :virtualbox do |v|
      v.name = "windows"
      v.memory = 2048
      v.cpus = 1
    end
  end
end

By the way, I am running this on Fedora 25.

Note that I tried to set my environment variable to no_proxy/NO_PROXY but still to no avail.
