### ISSUE TITLE
Support for OVF Properties in Vagrantfile at deployment time

### ISSUE THREAD

**Issue by tsugliani** [frapposelli/vagrant-vcloud#73]
Offer the capability to configure specific in guest application using the OVF properties of supported products.

Just thinking out loud a way to configure them:

``` ruby
  # Go through nodes and configure each of them.j
  nodes.each do |node|
    config.vm.define node[:hostname] do |node_config|
      node_config.vm.ovf.hostname = "great.hostname.com"
      node_config.vm.ovf.root_passwd = "amazing-password"
      node_config.vm.ovf.db_passwd = "awesome-password"
      node_config.vm.ovf.ssh_enabled = true
    end
  end
```

**Comment by gastoncan** [comment]
I think this enhancement [#73](https://github.com/frapposelli/vagrant-vcloud/issues/73) and [#82](https://github.com/frapposelli/vagrant-vcloud/issues/82) are related.
Both enhancements are very useful, avoiding to create a new box and uploading it (with the minimal property change) to the vCloud catalog.
@frapposelli  Is vcloud plugin version 0.5.0 planned to be released?
Thanks
